apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-config
  namespace: devops-app
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/to_db"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"
  TELEGRAM_BOT_TOKEN: "8214582880:AAFnIB94F9bH-m6SNRNR9ktGph5lGW_ZSZs"
  TELEGRAM_CHAT_ID: "931340901"

