name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assemble -Dorg.gradle.jvmargs=-Dfile.encoding=UTF-8

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifacts
          path: devops-backend/build/libs

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: devops-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run tests with Gradle
        run: ./gradlew check -Dorg.gradle.jvmargs=-Dfile.encoding=UTF-8
