name: CI Build and Push Docker Image

on:
  push:
    branches:
      - main
      - lab3
  pull_request:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup YC CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${{ secrets.YC_SERVICE_ACCOUNT_KEY_JSON }}" > key.json
          ./yc init --service-account-key key.json --profile default --non-interactive
          ./yc config set container-registry.registry-id ${{ secrets.YC_REGISTRY_ID }}

      - name: Cd to frontend folder
        run: |
          cd devops-front

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/frontend:1.0.0 .

      - name: Push Docker image
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/frontend:1.0.0